[package]
name = "library-example"
version = "0.1.0"
edition = "2021"

[dependencies]
graph-sql = { path = "../.." }
async-graphql = "7.0.11"
async-graphql-axum = "7.0.11"
axum = "0.8.4"
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.8.0", features = [
  "runtime-tokio-rustls",
  "sqlite",
  "migrate",
] }
anyhow = "1.0"

[[bin]]
name = "library"
path = "src/main.rs"
